### ISSUE TITLE
Translating actor names / placeholder

### ISSUE THREAD

**Issue by adokilume** [Ben987/Bondage-College#110]
While playtesting my progress on the german Kinbaku Club translation, I noticed the word "Unknown" in the spot where a character's name is usually displayed, if you don't know that character's name yet (I'm not sure how often that happens in the game, I just never noticed or thought about it before). This confused me at first, because as far as I know I've been through just about every translatable file in the game, until I found out that the "Unknown" string is hardcoded in Drawing.js.

Obviously this isn't a _huge_ deal, but it feels kinda weird to have that one English word there when everything else is translated.

This also made me think about name translations in general. It's not really a problem in my case since German uses the same letters as English, so all the character names are the same, but for languages like Russian or Chinese it might be a different story.

Would it be possible to add a global CSV somewhere that contains the English names as tags and the translated ones as content? Would that work if it's not really tied to any chapter?

**Comment by Ben987** [comment]
The unknown tag are for the twins, when you still don't know who is who.

Do you know where the all the "Unknown" shows?  We could ask wildsj to pull the tags from a file instead of plain text in code.

**Comment by adokilume** [comment]
I wasn't sure if it's only for the twins, I thought it might appear on ohter occasions when you haven't learned someone's name, but you probably have better knowledge on that. I just checked that it was indeed wildsj who added that line, but the thing is that it's not part of the Kinbaku Club itself.

It happens right inside the `DrawActorStats` function in Drawing.js, if the current Actor's `ActorHideName` is true. Since this is a global game function, I'm not sure if reading from a file would be possible without changing the structure or logic of that system. My first thought would have been to place the file somewhere inside the C999_Common folder, but Drawing.js isn't a part of that so I'm not sure if that's a clean way to do it.

A possible solution I'm thinking of right now might be to add a new value type to Actor.js, like `ActorDisplayName` or something like that (since the normal name is needed to identify the actor in the code, from what I can tell). Then, if that value is requested, the name could be looked up from a file, depending on current language and if the name should be hidden. Would that make sense? Sorry if I'm rambling, I'm still unsure about the details and there might be some things in the code I don't know about, plus I'm a bit tired at the moment.^^'

**Comment by Ben987** [comment]
Yes, you could certainly keep that translated value somewhere and show it instead of "Unknown".  The value could be pulled from the beginning of the game in one of the first files or some kind of new dictionary.

Is this something you would want to code?

**Comment by adokilume** [comment]
I think I could give it a try. Not sure if it's gonna work out the way I imagine, but I'll have a closer look at some of the code to see what can be done. I'm gonna finish translating the chapter first though (should be today or tomorrow), just to not get things mixed up.

**Comment by Ben987** [comment]
Sure, you can also leave the "unknown" tag for now.  German players won't mind too much.
