### ISSUE TITLE
Arousal screen character height

### ISSUE THREAD

**Issue by ace-1331** [Ben987/Bondage-College#1484]
The character in the arousal preference subscreen does not respect your height, it's believed to be a way to circumvent some limitations in how the zones are drawn for that page.

*Transferred from the redmine issue tracker as part of the issue migration*

**Comment by Nina-1474** [comment]
I always assumed this was just to make of the space on the screen and give a bigger target to click. There's no issues with making it apply the character's height if that's wanted but I think it actually looks a bit better without a gap above the character.
