### ISSUE TITLE
Framerate

### ISSUE THREAD

**Issue by ace-1331** [Ben987/Bondage-College#1485]
Some game functionalities are affected by framerate. 

Various minigames do not behave as expected under 60FPS and over 60FPS. Some have been fixed, but there are still some known/unknown ones.

*Transferred from the redmine issue tracker as part of the issue migration*

**Comment by elliesec** [comment]
One known issue that's recently been raised is the `DojoStruggle` minigame. The "bounce" goes higher and lasts longer at higher framerates (and conversely barely bounces at all when I tried it at 10FPS).
