### ISSUE TITLE
Duplicates from a File in "Bondage-College-master\C001_BeforeClass\FightIntro/"

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#164]
![grafik](https://user-images.githubusercontent.com/40240507/58761697-55ca3c00-8547-11e9-8a32-ae235a7272dc.png)

The file "Text_ES.cvs" is dopple. Please delet the old file.

Regards Dallun511

**Comment by Ben987** [comment]
Nice catch, thanks for letting me know :)
