### ISSUE TITLE
Lesbarkeit in BC

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#167]
![grafik](https://user-images.githubusercontent.com/40240507/58989480-49aeda80-87e4-11e9-8750-3212f701a9bf.png)

@adokilume Kann man dagegeben was machen oder müsste Ben was unternehmen?

**Comment by adokilume** [comment]
Oh, guter Fund! Eigentlich sind alle Dialoge auf die richtige Länge überprüft, aber offenbar hat bis jetzt noch niemand daran gedacht, dass der neue Stottereffekt, den @Lucritius12 eingebaut hat, ja die Länge verändert. Ich bin mir nicht sicher was da die eleganteste Lösung wäre, das werden wir mal im Discord-Server diskutieren.

**Comment by Dallun511** [comment]
@adokilume Ist mir schon lännger aufgefallen, aber ich dachte nur, dass es schon bekannt war, weswegen ich es jetzt melde.

Ich hätte sonst nur noch eine Frage. Warum nutzt du das TXT-Format und nicht das CSV, welches ich besser verstehe?

**Comment by adokilume** [comment]
Das mit dem TXT-Format hat sich aus einer längeren Diskussion mit Ben ergeben. Er wollte gern ein besseres Übersetzungs-System haben als im College. Das CSV-Format ist zwar gut, kann aber für viele unerfahrene Übersetzer ein Problem sein (wenn es irgendwo im Text ein Komma gibt, müssen z.B. Anführungszeichen richtig darum gesetzt sein). Außerdem enthalten die CSV-Dateien nicht nur Text, sondern auch Skript-Daten, die den Dialog-Verlauf bestimmen. Das bedeutet, das bei jeder Änderung der Originaldatei auch alle Übersetzungen sofort 1:1 angepasst werden müssen, weil sich das Spiel sonst nicht in allen Sprachen gleich verhalten würde. Die TXT-Datein funktionieren eher wie ein Wörterbuch, für jede englische Zeile genau eine Übersetzung. Das Spiel orientiert sich dann an der Originaldatei und schlägt die Übersetzungen einfach nach. Wenn eine Übersetzung noch nicht fertig ist, kann einfach automatisch der englische Text angezeigt werden ohne dass etwas schief läuft. Das macht es Entwicklern einfacher, neue Inhalte einzufügen, und als Übersetzer kann man sich auf das Wesentliche konzentrieren. :)

**Comment by Dallun511** [comment]
@adokilume ich danke dir für deine schnelle Antwort, denn ich habe es vorher nicht verstanden, warum die orig-datei immer CSV war, während die Übersetzungen TXT sind. Das hat mich verwirrt, aber jetzt kenne ich den Grund, aber ob ich klarkommen werde, weiß ich nicht. Sonst melde ich einfach weiterhin Bugs, die ich finde. Ich habe einen gefunden, den ich noch reproduzieren muss, um ihn erklären zu können.

**Comment by Ben987** [comment]
Try the latest version of the code, the text font will be smaller if it goes over the maximum number of lines allowed.
