### ISSUE TITLE
[Bug?] Unlock from ChasityItems

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#168]
@Ben987 Is it deliberate that the player can to unlock the Items "MetalChasityBelt" and "MetalChastityBra", although the sub weares her outfit?

![grafik](https://user-images.githubusercontent.com/40240507/59147729-64a96680-89ff-11e9-818a-e6f341b124f7.png)

**Comment by Ben987** [comment]
You're right, I haven't tested that part yet, I will correct it.  Thanks :)
