### ISSUE TITLE
[BUG?] "Straightjacket"

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#170]
I'm not sure whether it is a bug but save is save.

Why can i free my Sub although my sub had binded?
![grafik](https://user-images.githubusercontent.com/40240507/59291279-c75a6680-8c7a-11e9-82a8-cdff4d889cc8.png)

Or Why can i bind (**Torso**) my Sub although my sub had binded?
![grafik](https://user-images.githubusercontent.com/40240507/59291579-83b42c80-8c7b-11e9-8fef-567a5eb9d033.png)

The same for the "MetalChasityBelt".
![grafik](https://user-images.githubusercontent.com/40240507/59292071-89f6d880-8c7c-11e9-9cf5-ec54844f9c76.png)
![grafik](https://user-images.githubusercontent.com/40240507/59292115-a4c94d00-8c7c-11e9-9418-c52f254b31a1.png)

**Comment by Ben987** [comment]
Very true, I wonder why no one noticed it before.  Thanks, its fixed now, you're quite a tester :)
