### ISSUE TITLE
[Bug?] "cheat checkbox"

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#173]
![grafik](https://user-images.githubusercontent.com/40240507/59468347-126aaa00-8e32-11e9-9786-4334a3f96068.png)

Why is it not possible to use cheats? I can not enable the checkbox for a cheat to test it.
Wanted or not wanted?

**Comment by Ben987** [comment]
Sure it's possible, I publish a special cheaters version for Patreon users every time I release a version.  Don't worry, it works :)

**Comment by Dallun511** [comment]
The version worked a few versions ago, which surprises me but thanks for the informationen
