### ISSUE TITLE
[DE] Lesbarkeit 2

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#174]
![grafik](https://user-images.githubusercontent.com/40240507/59468936-9ffac980-8e33-11e9-8c0e-b5d8d7a35d49.png)

@adokilume Kann man das korrigieren, denn das ist kaum lesbar? Es wundert mich nur, dass dies niemand bisher gemedelt hat, weil das schon ein älteres Problem ist.

**Comment by adokilume** [comment]
Ich muss leider zugeben dass ich das nie wirklich getestet habe. Es ist mir erst heute bei den Klebeband-Knebeln aufgefallen, weil ich gerade die Übersetzungen auffrischen. Dass es auch hier ein Problem gibt wusste ich noch nicht. Ich kümmere mich darum, wahrscheinlich entferne ich einfach bei allen das Wort "fesseln". Für eine bessere Lösung müsste der Code geändert werden.

Es scheinen generell wenige Leute Feedback für die deutsche Version zu geben. Die meisten Fehler werden auf Discord gemeldet, aber die sind in der Regel eher allgemein. Von der deutschen Community bekomme ich persönlich irgendwie kaum etwas mit. Darum danke hierfür.^^

**Comment by Dallun511** [comment]
@adokilume Das ist wirklich schade, aber dann bin ich jetzt informiert und werde alles melden, was ich finde. Mir war nicht bewusst, dass die deutsche Community kaum was meldet.

**Comment by adokilume** [comment]
Ich bin mir nicht mal sicher wie groß die deutsche Community überhaupt ist. Auf dem Discord-Server des Spiels kenne ich ein paar Deutsche, aber die spielen eher auf Englisch.

**Comment by Dallun511** [comment]
Wer der Sprache mächtig ist, kann das von mir auch machen. Mein Englisch ist sehr begrenzt, weswegen ich alles nachschlagen müsste, weswegen ich froh bin, dass es überhaupt eine deutsche Übersetzung existiert und sogar supportet wird.

**Comment by Ben987** [comment]
Could you put some abbreviations or smaller words for these captions?

**Comment by adokilume** [comment]
Just did, coming tomorrow once I finish translating the rest of the new/changed lines.^^
