### ISSUE TITLE
bondagecomixxx

### ISSUE THREAD

**Issue by Homanei** [Ben987/Bondage-College#1852]
account need!???

**Comment by elliesec** [comment]
Only the Bondage Club browser game requires an account to play. 

The two comics: Bondage Club and Bondage Roommates do not need any account, and neither does the Bondage College browser game. If you're seeing an account login prompt, it's likely to do with your internet setup (e.g. VPN/ISP provider).

**Comment by elliesec** [comment]
Given your account's history, I have doubts that this issue pertains directly to this repository, and am closing the issue.
