### ISSUE TITLE
Dom and Sub at the same time?

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#189]
Is it wanted that one can be Dom and Sub at the same time?
![grafik](https://user-images.githubusercontent.com/40240507/59887477-c2f12480-93c3-11e9-9579-5d8ece140ba3.png)
German "Herrin" = "Misstress" in english
![grafik](https://user-images.githubusercontent.com/40240507/59887513-f16eff80-93c3-11e9-8f01-2b5f1270a6a5.png)

**Comment by adokilume** [comment]
Yes, you can become someone's sub and then level up your dominance to become a mistress. There's even dialogue lines your own subs can only say if you have an owner.

**Comment by Dallun511** [comment]
Kann man nur so eine Liebhaberin kriegen? Habe mich immer gefragt, wie das geht.

**Comment by Ben987** [comment]
Sure, it's an unusual path but there's no problem there.

**Comment by adokilume** [comment]
@Dallun511 Eine Liebhaberin kann man im Moment nur haben, wenn man aus dem College kommt (Amanda, Sarah, Sidney, Jennifer) oder indem man am Code herumspielt. Später wird es wahrscheinlich auch Möglichkeiten im Club selbst geben.

(@Ben987 : Just explaining the "Lover" thing, in case you're wondering.)
