### ISSUE TITLE
have a bug with limitedItems

### ISSUE THREAD

**Issue by DoberBit** [Ben987/Bondage-College#1895]
https://github.com/Ben987/Bondage-College/blob/1267c61154b7acaa56123dda90b4f0b703c5c64b/BondageClub/Scripts/Inventory.js#L889
if difficulty is Extreme and premmision: owner, lover and white list then white list can't lock password or combination padlock
Please change if C.ItemPermission < 3 to C.ItemPermission <= 3

**Comment by Nina-1474** [comment]
This is by design. If you allowed people on your whitelist to use limited items when your permissions are "Owner, Lover and whitelist only", then making items limited becomes meaningles, since everyone who can interact with you can then also use limited items.
At permission level 3, items being limited becomes an 'owner and lovers only' setting.

**Comment by Nina-1474** [comment]
Those two locks are automatically set to limited for the extreme difficulty since it's too easy for griefers to irreversibly lock someone otherwise. A possible solution could be not making them limited when at permission level 3.

**Comment by DoberBit** [comment]
> owner and lovers only

I did not understand where "only the owner and amateurs" is involved if this permission has id 4

**Comment by Nina-1474** [comment]
I meant only the limited items become owners and lovers only. Here's a table to make it a bit clearer:

```
Level | Permissions                         | Limited items are accessible to
-----------------------------------------------------------------------------
0     | Everyone, no exceptions             | Owner, Lover and whitelist
1     | Everyone, except blacklist          | Owner, Lover and whitelist
2     | Owner, Lover, whitelist & Dominants | Owner, Lover and whitelist
3     | Owner, Lover and whitelist only     | Owner and Lover
4     | Owner and Lover only                | Owner and Lover
5     | Owner only                          | Owner
```

**Comment by DoberBit** [comment]
> I meant only the limited items become owners and lovers only. Here's a table to make it a bit clearer:
> 
> ```
> Level | Permissions                         | Limited items are accessible to
> -----------------------------------------------------------------------------
> 0     | Everyone, no exceptions             | Owner, Lover and whitelist
> 1     | Everyone, except blacklist          | Owner, Lover and whitelist
> 2     | Owner, Lover, whitelist & Dominants | Owner, Lover and whitelist
> 3     | Owner, Lover and whitelist only     | Owner and Lover
> 4     | Owner and Lover only                | Owner and Lover
> 5     | Owner only                          | Owner
> ```

i'm known this, but i did don't undesrstand why white list can't lock password or combination padlock if i have "Extrime" and permission "Owner, Lover and whitelist only"
Maybe i is stupid?

**Comment by elliesec** [comment]
Because when you select Extreme mode, those two locks automatically get individually set to limited permissions for safety (meaning whitelist won't be able to use them if you're using "Owner, Lover and whitelist only" global permissions). You should still be able to change them back to open permissions if you wanted.

**Comment by DoberBit** [comment]
> Because when you select Extreme mode, those two locks automatically get individually set to limited permissions for safety (meaning whitelist won't be able to use them if you're using "Owner, Lover and whitelist only" global permissions). You should still be able to change them back to open permissions if you wanted.

But if i selected permissions to "Owner, Lover, whitelist & Dominants" then all worked

**Comment by elliesec** [comment]
Check Nina's table - "Owner, Lover, whitelist & Dominants" maps to "Owner, Lover and whitelist" for limited items. Try setting the individual item permissions to not be limited (green).

**Comment by DoberBit** [comment]
> Check Nina's table - "Owner, Lover, whitelist & Dominants" maps to "Owner, Lover and whitelist" for limited items. Try setting the individual item permissions to not be limited (green).

i have a "Exrime" and don't have access to item premission

**Comment by Nina-1474** [comment]
You can't change item permissions in the Extreme difficulty. I have a change ready so that the locks are not set to limited when you're on Owner/Lover/Whitelist permissions, since it stands to reason that you'd trust your whitelist.

**Comment by elliesec** [comment]
I forgot about item permissions in extreme mode. I still find that particular restriction... strange.

**Comment by DoberBit** [comment]
> I forgot about item permissions in extreme mode. I still find that particular restriction... strange.

otherwise it would be boring

**Comment by DoberBit** [comment]
Perfect! I'm liked this!

**Comment by DoberBit** [comment]
Don't know if the question needs to be closed in this issue?

**Comment by DoberBit** [comment]
> Once the linked PR is merged this will be closed automatically!

Thanks!
