### ISSUE TITLE
[BUG] Full Dress

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#200]
![grafik](https://user-images.githubusercontent.com/40240507/60929283-ff23f080-a2b0-11e9-8432-868407cbf983.png)

![grafik](https://user-images.githubusercontent.com/40240507/60929302-0fd46680-a2b1-11e9-9e8b-85d9fd97ba3e.png)

**Comment by Ben987** [comment]
What's the bug exactly?  Did you went shopping with her and removed her clothes?  I that case, she won't be able to get fully dressed back, you'll need to go shopping again.

**Comment by Dallun511** [comment]
nop, i don't shoppping. she had the school uniform last

**Comment by Ben987** [comment]
If you get a new girl and you try to undress/dress her, do you get the same problem?

**Comment by Dallun511** [comment]
no, only old Gils

**Comment by Ben987** [comment]
Don't worry about it then, it could be related to invalid data from a previous version.
