### ISSUE TITLE
[DE] Update für Übersetzung

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#201]
![grafik](https://user-images.githubusercontent.com/40240507/60929591-39da5880-a2b2-11e9-9d10-a7ef61dc58b6.png)

@adokilume das scheint veraltet zu sein.

Grüße Dallun511

**Comment by adokilume** [comment]
Guter Fund, tatsächlich ist das im Englischen aber auch noch so, sonst hätte mein Tool mir schon gemeldet, dass es eine Änderung gab. Es könnte eventuell auch Absicht sein, weil das Zimmer an sich (ohne Erweiterung) ja wirklich nur 4 Plätze hat.

@Ben987
Is the line "`Of course. The room isn't huge though, it will not fit more than 4 people.`" something you forgot to change after adding the room extensions, or does it just mean the room by itself?

**Comment by Ben987** [comment]
The text was changed.
