### ISSUE TITLE
[BUG?] Index.htlm brocken?

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#204]
![grafik](https://user-images.githubusercontent.com/40240507/61100434-7353c500-a466-11e9-9b4d-d2fc17ed0c9e.png)

**Comment by Ben987** [comment]
It works fine on my side.  Make sure you have all the latest files.

**Comment by Dallun511** [comment]
@Ben987 redownload und again

![grafik](https://user-images.githubusercontent.com/40240507/61163027-e6fbdd80-a50b-11e9-9189-63e436ecf0da.png)

**Comment by Ben987** [comment]
There's probably something wrong in your setup.  It works fine on my side.  You can try to show the javascript errors, maybe it will give a clue.

**Comment by Dallun511** [comment]
![grafik](https://user-images.githubusercontent.com/40240507/61166941-d44ace00-a536-11e9-916c-9566fe461353.png)

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Assets/Female3DCG/Female3DCG.csv. (Grund: CORS-Anfrage war nicht http).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Login/Text_Login.csv. (Grund: CORS-Anfrage war nicht http).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Player/Dialog_Player.csv. (Grund: CORS-Anfrage war nicht http).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Login/GameCredits.csv. (Grund: CORS-Anfrage war nicht http).

SecurityError: The operation is insecure. Drawing.js:197
    DrawImageCanvasColorize file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:197
    CharacterAppearanceBuildCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Appearance/Appearance.js:291
    CharacterLoadCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Character.js:363
    CharacterLoadCanvasAll file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Character.js:371
    onload file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:71
Connected to the Bondage Club Server Server.js:9:61
SecurityError: The operation is insecure. Drawing.js:197
    DrawImageCanvasColorize file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:197
    CharacterAppearanceBuildCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Appearance/Appearance.js:291
    CharacterLoadCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Character.js:363
    CharacterAppearanceFullRandom file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Appearance/Appearance.js:173
    LoginDoNextThankYou file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Login/Login.js:14
    LoginRun file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Login/Login.js:97
    CommonDynamicFunction file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Common.js:147
    DrawProcess file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:511
    MainRun file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/index.html:143
SecurityError: The operation is insecure. Drawing.js:197
    DrawImageCanvasColorize file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:197
    CharacterAppearanceBuildCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Screens/Character/Appearance/Appearance.js:291
    CharacterLoadCanvas file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Character.js:363
    CharacterLoadCanvasAll file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Character.js:371
    onload file:///C:/Users/Dallun511/Downloads/Bondage-College-master(8)/Bondage-College-master/BondageClub/Scripts/Drawing.js:71

**Comment by Dallun511** [comment]
@Ben987 Regardless of whether Firefox or Chrome the html is brocken. Redownload brings nothing. Update also.

**Comment by Ben987** [comment]
Your local setup might be incorrect, that's why you're getting these CORS security errors.

Try to run the site using a local web server.  Windows IIS or XAMP would work.

**Comment by 1nsp1rat1on** [comment]
Have the same problem with Firefox and Google Chrome

**Comment by Ben987** [comment]
If your local security doesn't allow you to run the website locally, use a local web server such as IIS or XAMP.

**Comment by 1nsp1rat1on** [comment]
Are you sure you didnt change somethink? Didnt have this problem before with Firefox .

**Comment by Ben987** [comment]
Firefox changed it's security settings in the latest update.  You can go in the Firefox panel to change it back, I'm not sure of the name of the option though.

**Comment by 1nsp1rat1on** [comment]
It`s the new Firefox version. Did a downgrade and now it works again. Maybe you can fix it sometimes.
Here is an article for the change who is the problem https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by Ben987** [comment]
I understand why Firefox does this, other browsers also do it to protect local files.  I can't really change the code on my side though, people will need to use the old Firefox or setup a local webserver.

**Comment by Dallun511** [comment]
[Bondage-Club-Bug.zip](https://github.com/Ben987/Bondage-College/files/3425257/Bondage-Club-Bug.zip)
![grafik](https://user-images.githubusercontent.com/40240507/61769537-e5bf9000-adea-11e9-993c-2c9acc71579a.png)

Three Browser and all same Bug

**Comment by Ben987** [comment]
Correct, you need to setup a local webserver (IIS, Apache, Xampp) or change your Firefox settings.

**Comment by gottspende** [comment]
For Firefox > about:config (in the adress bar) -> I take the Risk -> look in the research bar the value "privacy.file_unique_origin" then turn Value "True" to "false" then Reload the browser it should work
My firefox is not in english but it's near of the process to be done.

**Comment by Dallun511** [comment]
Yes, it fix the problem, but don't use this by my main Firefoxe.
Thank you for this Tipp
