### ISSUE TITLE
[BUGs]not playable, in fact online

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#215]
![grafik](https://user-images.githubusercontent.com/40240507/61407619-79222e00-a8de-11e9-90a5-2f0081f0fdb2.png)

![grafik](https://user-images.githubusercontent.com/40240507/61407646-84755980-a8de-11e9-9759-99c19014b3eb.png)

That does not happen to me if I have the data with me

**Comment by Ben987** [comment]
What's the bug exactly?  Do you have some console error messages?

**Comment by Dallun511** [comment]
Mache ich beim nächsten Mal, denn das passiert oft.
Doch bringt es dir was, wenn die Konsole auf Deutsch ist?

**Comment by Ben987** [comment]
I cannot help you much in German.

**Comment by Dallun511** [comment]
Is updated

**Comment by Ben987** [comment]
Having the error in German probably won't help, I'll need it in English to help you.

**Comment by Ben987** [comment]
Anything I can do on that bug report?  Can we close it?

**Comment by gamer29345** [comment]
i been loking for this game can u send me a link

**Comment by zorgjbe** [comment]
@gamer29345 Here: https://www.bondageprojects.com/
Click "Bondage Club", then choose the hosting server closest to you. You should be set.
