### ISSUE TITLE
China region cannot connect to the server

### ISSUE THREAD

**Issue by sakurua2756** [Ben987/Bondage-College#2594]
Everything is fine on the web page, but I can't log in and can't connect to the server.
![W )I03KPO(5GTC@0}}J1TAV](https://user-images.githubusercontent.com/80534056/122644734-598a8480-d149-11eb-8c34-4cdcd89fb8b3.png)

**Comment by sakurua2756** [comment]
Add: everything is fine after hanging the vpn

https://user-images.githubusercontent.com/80534056/122644914-2b597480-d14a-11eb-8970-ec25a97c36cd.mp4

It behaves strangely and doesn't need to connect to the vpn the whole time, just at login.

**Comment by RXLX-CHINA** [comment]
我也是，我这边应该是中国电信，挂了VPN好像也上不去，有办法吗
