### ISSUE TITLE
Schreibfehler entdeckt

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#293]
![grafik](https://user-images.githubusercontent.com/40240507/64061673-54f48500-cbde-11e9-8e69-fea8c467a997.png)
@adokilume Beim nächsten Patch bitte beheben.

**Comment by Ben987** [comment]
Is this resolved?  Can I close it?

**Comment by Dallun511** [comment]
Nope, the error is still there

But that fixes it #306

**Comment by adokilume** [comment]
(Sorry for not reacting to this, I would have fixed it the next time I did translations, but thanks for taking care if it :) )
