### ISSUE TITLE
Wiki page: Adding new… Dialogs

### ISSUE THREAD

**Issue by karame1** [Ben987/Bondage-College#3189]
I don't know if there is a way to suggest wiki editions with github. So I submit it though an issue, please let me know if there is a better way to do so. I've set a local repository for the wiki, I could send commit patches.

I took some notes when first editing an existing dialog while reading some code from the engine. Attached is the page that could be put into https://github.com/Ben987/Bondage-College/wiki/NewDialog

Those notes are still incomplete, but I'm currently not working on dialogs so I won't touch it before some time. So it could be a starting point if someone would like to expand it.

[NewDialog.md](https://github.com/Ben987/Bondage-College/files/7876857/NewDialog.md)

**Comment by Ben987** [comment]
I don't think anyone is checking these issues, Let's close this for now.
