### ISSUE TITLE
Hum...I cannot connect the website.

### ISSUE THREAD

**Issue by RXLX-CHINA** [Ben987/Bondage-College#3302]
As I had play this game for about one year and a half, but recently, I cannot load this webpage, maybe my DNS server has banned your website, I want to know if there's any solution just like a backup website or anothor IP address? Love your game and want to return online. Thanx and waiting for reply~

**Comment by have19713** [comment]
I can connect the server in China,and my DNS server is Jiangsu Mobile.So I think it's your DNS server's problem.

**Comment by Ben987** [comment]
Please submit these errors on Discord.
