### ISSUE TITLE
Potential "Futuristic Panel Gag" design oversight.

### ISSUE THREAD

**Issue by sageforce** [Ben987/Bondage-College#3504]
While the "Futuristic Panel Gag" is in its "Padded" mode it doesn't allow "mouth" or "gaged" actions to be performed.

it would make sense that you could still do the "gaged" actions even if it isn't inflated.

this applies to both the "Futuristic Panel Gag" and the "Futuristic Harness Panel Gag".
is this a known issue? i couldn't find any mention of it here.

**Comment by Ben987** [comment]
Hello, this is not the best place to post reports like that, please use Discord.
