### ISSUE TITLE
Maybe use GitFlow?

### ISSUE THREAD

**Issue by project-am** [Ben987/Bondage-College#4]
It allows for better version control, which might be nice, especially if you hope for many people contributing code, testing it and then releasing it in a controlled fashion as a new version. You can read more about it here: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by Ben987** [comment]
Yes, starting from the next chapter, if there are many developers that joins, I'll probably do a master branch for main releases and a develop branch for day to day development.  I still don't know how many people will participate though.  Thanks! :)
