### ISSUE TITLE
Rechtschreibtfehler gefunden.

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#428]
![grafik](https://user-images.githubusercontent.com/40240507/66772782-cd2cb680-eebd-11e9-8212-5093eecf1db2.png)
Dieser ist mir ins Auge gefallen. Ich suche weiter.

**Comment by adokilume** [comment]
Alles klar, vielen Dank! Da ich gerade erst eine Portion Übersetzungen hochgeladen habe, behebe ich den wahrscheinlich in ein paar Tagen, wenn es noch ein paar mehr Texte zu ergänzen gibt.

(This is a typo I'll correct with the next batch of translations.)

**Comment by Ben987** [comment]
Alright Ado.  Good luck with that.
