### ISSUE TITLE
slave collar graphic bugs

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#499]
Moin/Hello

![grafik](https://user-images.githubusercontent.com/40240507/69714843-7d215080-1107-11ea-996e-33acf24e15a6.png)
"Maid Collar"
![grafik](https://user-images.githubusercontent.com/40240507/69714864-87dbe580-1107-11ea-90ef-40ff2cdd7ff9.png)
"Bat Colloar"

Here are two graphic bugs.

Regards
Dallun511

**Comment by Ben987** [comment]
I'll be reworking the slave collar later today or tomorrow to fix lots of stuff.
