### ISSUE TITLE
Item Bug "Bondage Bench"

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#500]
Moin/hello

I report a bug
![grafik](https://user-images.githubusercontent.com/40240507/69715177-1a7c8480-1108-11ea-82dd-b52d58bae31d.png)
This item can not be removed

Regards
Dallun511

**Comment by Serunati42** [comment]
you can its just in the section where you can see the locks you own

**Comment by Dallun511** [comment]
Thx for the Information
