### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#581]
Hello/moin
![jpg](https://user-images.githubusercontent.com/40240507/72664827-cd7ba700-3a02-11ea-82ef-f374907c8b56.jpg)

I cannot test a "beta".
I get stuck at login.

Can you help me?

Regards
Dallun511 Ferewo

**Comment by Ben987** [comment]
Check your console log to see the error, the latest browsers do not allow to run javascript locally anymore.

**Comment by Dallun511** [comment]
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: file:///C:/Users/Dallun511/Downloads/Bondage-College-master(2)/Bondage-College-master/BondageClub/Assets/Female3DCG/Female3DCG.csv
Zeile Nr. 1, Spalte 1: Female3DCG.csv:1:1
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: file:///C:/Users/Dallun511/Downloads/Bondage-College-master(2)/Bondage-College-master/BondageClub/Screens/Character/Login/Text_Login.csv
Zeile Nr. 1, Spalte 1: Text_Login.csv:1:1
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: file:///C:/Users/Dallun511/Downloads/Bondage-College-master(2)/Bondage-College-master/BondageClub/Screens/Character/Player/Dialog_Player.csv
Zeile Nr. 1, Spalte 1: Dialog_Player.csv:1:1
XML-Verarbeitungsfehler: Syntax-Fehler
Adresse: file:///C:/Users/Dallun511/Downloads/Bondage-College-master(2)/Bondage-College-master/BondageClub/Screens/Character/Login/GameCredits.csv
Zeile Nr. 1, Spalte 1: GameCredits.csv:1:1

**Comment by Ben987** [comment]
Your browser might not allow you to run javascript locally anymore.  You might need to setup a local webserver like most of us or mess with security.  Try to ask around on Discord, you'll get more help.  Thanks!
