### ISSUE TITLE
Graphics error by Amanda

### ISSUE THREAD

**Issue by Dallun511** [Ben987/Bondage-College#630]
Hello,

I report a Bug.
![grafik](https://user-images.githubusercontent.com/40240507/73602983-fbbdc280-457c-11ea-9903-bcbd10582fc4.png)
Amanda has a rope over their head, this is the bug.

**Comment by EveFerox** [comment]
Describe how to reproduce it

**Comment by Dallun511** [comment]
difficult, because I don't know how I provoked him
but I'll try to re-enact

**Comment by Ben987** [comment]
Let us know on discord if you can recreate it, I don't really monitor this board.
