### ISSUE TITLE
Prison issue 

### ISSUE THREAD

**Issue by Jenni19** [Ben987/Bondage-College#678]
Hey,
I found a logical bug in the prison scene. 

Steps to reproduce:
- go to the prison
- tie up the maid there (you need to be a head maid to do so)
- put handcuffs on yourself
- talk to the maid and ask "What kind of test is it?"

Even if the maid is fully restrained, she'll put you in the cell and the game starts. 
In addition, if you gag the maid, the dialog says that she puts you in the cell, but nothing more happens. 

It's just a logical bug as a tied up maid shouldn't be able to push you in the cell :)

**Comment by Ben987** [comment]
There's a few bugs in the prison, but don't put them here, git4nick will not be able to see them.  Send them to git4nick on DeviantArt.  Thanks!
