### ISSUE TITLE
Change how 1 minute interactions work?

### ISSUE THREAD

**Issue by adokilume** [Ben987/Bondage-College#68]
This issue might not be that big of a deal, I'm pointing it out just in case.

While browsing the code, I found the following line (Common.js line 250 at the time of writing):
`if (CurrentStage[L][StageInteractionText].indexOf("(1 minute)") >= 0) CurrentTime = CurrentTime + 60000;`

Apparently the game checks if the interaction string contains the string "(1 minute)" to determine if the action takes 60 or the default 10 seconds. This is a bit of a problem because it's not translation proof. For example, I translated some files to German without knowing this and changed "(1 minute)" to "(1 Minute)" - the only difference is the uppercase M, but it's still a difference and so the action takes 10 seconds, rather than 60 as it states. The Chinese translation has the same problem in a much more obvious way.

You could just check for different substrings depending on the language, but I'm not sure it's a good idea in general if the game is pulling information from the same text the player sees. I've had to shorten a few instances of "(1 Minute)" to "(1 Min.)" or even just "(1)" in German because the actual interaction was already almost too long to fit in the buttons and there was no sane way to make it shorter, so in those cases the timing would fail anyway, unless you checked for multiple strings for each language.

Maybe there should be some kind of marker character in the string that tells the game that it's a 1 minute interaction, but gets removed before it's rendered on the screen. Or maybe a new CSV column for the duration, and if it's omitted the game would just assume the default 10 seconds. This would also allow for interactions of more varying length without too much coding effort, though adjusting all those CSV files might be a pain.

In the end it all comes down to whether or not it's actually important how long an interaction takes. I didn't even notice this was happening until I saw the code.

**Comment by Ben987** [comment]
Yes, I don't like how the (1 minute) interactions work either, that's why I don't use it anymore in my latest code.  Ideally, I would remove it everywhere and add some code to add 1 minute or add another hidden tag to speed up the time by X minutes.  If you want, we could add a special tag like the COMMON_PLAYERNAME and remove that tag from the screen but add the time.  Something like MINUTE1, MINUTE5, MINUTE15 could work.  That number of minute doesn't need to be shown in advance to the player.

**Comment by Ben987** [comment]
Sure, you could code a "ADD_MINUTE_X" hidden tag if you want and use it to play with the time depending on the answer given.  It should be fairly easy to code and to use.  Do you want to add and test it?  Thanks.
