### ISSUE TITLE
[BUG] overwritten chastity

### ISSUE THREAD

**Issue by Fox906090** [Ben987/Bondage-College#786]
In the club management, if you annoy the dom and you wear a chastity belt and bra (which of course might be owner locked or the love chastity belt), they'd get overwritten by the dom's gear. 

I think, there should be some ifs at "ManagementPlayerRandomRestrain()" in BondageClub/Screens/Room/Management.js Line 162-169

**Comment by Ben987** [comment]
Please post the errors you find on Discord, I don't think anyone is checking these boards.  Thanks!
