### ISSUE TITLE
[BUG] Chastity Piercings

### ISSUE THREAD

**Issue by Fox906090** [Ben987/Bondage-College#787]
Chastity piercings can't be unlocked by the dom in the club management (you can just pay 25$ over and over again, but the piercing stays on)

**Comment by Fox906090** [comment]
Same applies if you want to free a npc in the private room: You may pay the 25 $, but nothing happens.

**Comment by Ben987** [comment]
Please post the errors you find on Discord, I don't think anyone is checking these boards.  Thanks!
