### ISSUE TITLE
[BondageClub] Maid sorority dead-end (Firefox)

### ISSUE THREAD

**Issue by Ryotaiku** [Ben987/Bondage-College#88]
When signing up to be a full maid in the sorority, you're supposed to be bound and paddled. But after you're bound, you get stuck on a blank screen with nothing happening. If you quit and reload the game, your outfit is reset and you're left stuck in the gear you were bound in.

**Comment by Ben987** [comment]
Which browser are you using?  I've tried it before and it works.  Maybe it's browser related.

Can you try to force reload (CTRL+R) or empty your cache for the website?  It could also work.

**Comment by Ryotaiku** [comment]
> 
> 
> Which browser are you using? I've tried it before and it works. Maybe it's browser related.
> 
> Can you try to force reload (CTRL+R) or empty your cache for the website? It could also work.

I'm using Firefox, and have edited the title to reflect that. I'm also running from the standalone download here on Github, since the website hangs on the login screen without any progression. But that's a separate issue and could get its own thread.

**Comment by Ben987** [comment]
I've just tried it with Firefox and everything works, I was able to get through the maid initiation without issues.  There might be something else that's preventing you from the running properly.  If your network or computer doesn't allow you to run adult websites, it could cause problems with the game.

**Comment by Ryotaiku** [comment]
I'm not restricted on using adult websites. If it was, I couldn't even access the login page. The only other variable I can think of is the chastity belt, as there's currently no way to remove it. Could that be causing issues?

**Comment by Ben987** [comment]
Can you try with Chrome?  I do most of my tests on Chrome, maybe you'll get better results.

**Comment by Ryotaiku** [comment]
Well Chrome just shows some even more weird behavior. The website works properly through Chrome, but the standalone doesn't load things correctly on the login page, effectively making it online-only if you're not using Firefox. I think I'll just close this thread and open a new one for general compatibility issues.
