### ISSUE TITLE
[BondageClub] Compatibility issues

### ISSUE THREAD

**Issue by Ryotaiku** [Ben987/Bondage-College#89]
This is a thread for listing any problems users encounter while playing Bondage Club; based on their web browser, the website, or the standalone download hosted here on GitHub. The items listed here are only things that I've experienced, but feel free to list anything you've observed as well.
### Firefox
- ~~**Website**: Attempting to log in hangs on validating name and password, rendering the game unplayable. You can reach the lobby by making a new character, but trying to enter any other area will cause the game to hang.~~ Turns out all that was interfering was my adblocker. As far as I'm aware the site doesn't have ads, so you're at no risk by leaving it turned off.
- **Standalone**: Attempting to become a full maid in the sorority is supposed to bind and paddle the player, but simply freezes in the maid quarters without progressing. Seeing as this works fine in Chrome, it could be a dialogue issue with Firefox.

### Chrome
- **Standalone**: Text, avatar acknowledgements, and buttons don't load. This prevents the player from logging in at all.

These are only the issues I've run into, and is certainly not a complete list, and I'll be updating it as I find more problems. I want to see this game succeed, and one step to seeing that happen is to make sure it behaves correctly on everything.

**Comment by Ben987** [comment]
I don't really support "standalone" version of the game, it's meant to be played online.   But I can try to help you with your local setup.  

To run the game on my side, I've setup a IIS server and I run the game by calling my local server: http://localhost/BondageClub/

Is this the way you've setup your installation?  Can you try it?
