### ISSUE TITLE
VibratingEgg Regression

### ISSUE THREAD

**Issue by project-am** [Ben987/Bondage-College#9]
In C003, when taking the egg, there is a JS error:

```
Common.js:151 Trying to launch invalid function: C999_Common_VibratingEgg_Load()
```

Caused by clicking on the egg in the inventory. I suspect that the regression was introduced in your latest commit. I played through all chapters and was able to give the egg to everyone else on all other occasions, so it seems only C003 is affected.

The problem is, that you only have "Egg" functions, while you named the item "VibratingEgg", so when checking for the clicked item, `GetClickedInventory()` returns the name of the item and not the name needed for the functions in Common. Putting `if (Inv === 'VibratingEgg') Inv = 'Egg';` at the end as a workaround seems to prevent all other Egg-events to function (with the exception of putting it into yourself). Unfortunately, I am low on time during the next few weeks, so I was not able to provide a fix-PR. I hope you can sort that one out, since you should be more familiar with the code base than I am.

**Comment by Ben987** [comment]
Thanks!  I'll fix it soon :)

**Comment by Ben987** [comment]
This one is already correct :)
